//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetPrivilegio
    {
        public int ID_ROL { get; set; }
        public int ID_OPCION { get; set; }
        public string OPCION { get; set; }
        public string rol { get; set; }
        public string ACCESO { get; set; }
        public string AGREGAR { get; set; }
        public string EDITAR { get; set; }
        public string ELIMINAR { get; set; }
    }
}
