//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iu_opcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public iu_opcion()
        {
            this.iu_rol_menu = new HashSet<iu_rol_menu>();
        }
    
        public int ID_OPCION { get; set; }
        public string OPCION { get; set; }
        public string URL { get; set; }
        public int ID_MENU { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
    
        public virtual iu_menu iu_menu { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iu_rol_menu> iu_rol_menu { get; set; }
    }
}
