//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCierre
    {
        public int IDPERIODO { get; set; }
        public Nullable<int> IDTIPOSALDO { get; set; }
        public int IDNIVEL { get; set; }
        public string NUMEROCUENTA { get; set; }
        public Nullable<double> SALDOCIERRE { get; set; }
    
        public virtual tblcuenta tblcuenta { get; set; }
        public virtual tblPeriodo tblPeriodo { get; set; }
        public virtual tbltiposaldo tbltiposaldo { get; set; }
    }
}
