//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldetallepartida
    {
        public string IDPARTIDA { get; set; }
        public int IDNIVEL { get; set; }
        public string NUMEROCUENTA { get; set; }
        public short NUMERODETALLE { get; set; }
        public double PARCIAL { get; set; }
        public double DEBE { get; set; }
        public double HABER { get; set; }
    
        public virtual tblcuenta tblcuenta { get; set; }
        public virtual tblmaestropartida tblmaestropartida { get; set; }
    }
}
