//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmovimiento
    {
        public Nullable<int> IDNIVEL { get; set; }
        public string NUMEROCUENTA { get; set; }
        public string IDPARTIDA { get; set; }
        public int IDMOVIMINETO { get; set; }
        public Nullable<System.DateTime> FECHA_MOVIMIENTO { get; set; }
        public Nullable<double> MONTO_MOVIMIENTO { get; set; }
    
        public virtual tblmaestropartida tblmaestropartida { get; set; }
        public virtual tbltipomovimiento tbltipomovimiento { get; set; }
    }
}
