//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaMenu
    {
        public int ID_MENU { get; set; }
        public string MENU { get; set; }
        public string ICONO { get; set; }
        public Nullable<int> MOVIL { get; set; }
    }
}
