//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaOpcione
    {
        public int ID_OPCION { get; set; }
        public string opcion { get; set; }
        public string MENU { get; set; }
        public string VISTA { get; set; }
        public string CONTROLADOR { get; set; }
    }
}
